### ISSUE TITLE
TODO #1 : Equipaggio entita' debole?

### ISSUE THREAD

**Issue by igorsvara** [thomasmassarutto/Voli_Aeroporto#4]
Nella relazione bisogna scrivere perche' abbiamo deciso di introdurre per l'entita' equipaggio un id e perche' non l'abbiamo resa un'entita' debole ~> (1,N e 2,2) dovrebbero essere (1,1)

**Comment by thomasmassarutto** [comment]
Si può scrivere nella relazione secondo me
